[package]
name = "trylep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.3", features = [
    "stable",
    "serde",
    "csr",
]}
leptos_meta = { version = "0.3", features = ["stable", "csr"] }
leptos_router = { version = "0.3", features = ["stable", "csr"]  }
log = "0.4"
gloo-net = { version = "0.2", features = ["http"] }
serde_qs = "0.12"
serde_urlencoded = "0.7.1"


# dependecies for client (enable when csr or hydrate set)
wasm-bindgen = { version = "0.2" }
console_log = { version = "1"}
console_error_panic_hook = { version = "0.1"}
serde = { version = "1.0.164", features = ["derive"] }
web-sys = { version = "0.3.64", default-features = false, features = ["FormData"] }
serde_json = "1.0.97"
